openapi: 3.0.3
info:
    title: Goa API
    version: 0.0.1
servers:
    - url: http://localhost:80
      description: Default server for portfolio
paths:
    /portfolio/summary:
        get:
            tags:
                - portfolio
            summary: getPortfolioSummary portfolio
            operationId: portfolio#getPortfolioSummary
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/PortfolioSummary'
                            example:
                                balance: 0.8755333377922939
                                change_percent: 0.023360215353720726
                                currency: Aut culpa consequatur necessitatibus.
components:
    schemas:
        PortfolioSummary:
            type: object
            properties:
                balance:
                    type: number
                    description: Total Balance
                    example: 0.47723201288775363
                    format: double
                change_percent:
                    type: number
                    description: Change Percentage
                    example: 0.2604217807206088
                    format: double
                currency:
                    type: string
                    description: Currency Code
                    example: Quia ratione aliquam consectetur sunt amet non.
            example:
                balance: 0.12847725005648608
                change_percent: 0.061940674743277156
                currency: Nisi sit.
            required:
                - balance
                - currency
                - change_percent
tags:
    - name: portfolio
      description: Portfolio API
